### ISSUE TITLE
Basic example doesn't work upon copy-and-paste

### ISSUE THREAD

**Issue by danlynkew** [scrumpy/tiptap#134] opened 2018-12-13 14:56 UTC
I want to use Tiptap as a rich-text editor in my Vue app. I'm having trouble getting the basic example working.

I’ve run `npm install tiptap tiptap-extensions` and copied-and-pasted the  `tiptap/examples/Components/Routes/Basic/index.vue` code into one of my Vue components. I’m getting the following error:

```
This dependency was not found:
* Components/Icon in ./node_modules/...
```

It seems to be related to line 132: `import Icon from 'Components/Icon’`

How can I get the basic example working?

**Comment by strixy** [comment] 2018-12-13 21:10
I had a similar experience. [See this issue for details](https://github.com/scrumpy/tiptap/issues/125#issuecomment-445580924 ) and some advice on how to go about solving your use case. tldr; create your own component or check the example for the Icon component and c/p that too.

**Comment by hanspagel** [comment] 2018-12-13 21:34
I'm closing this, as it's a duplicate of #125.

**Closed by hanspagel** 2018-12-13 21:34 UTC

**Comment by danlynkew** [comment] 2018-12-13 21:40
Wait, I'd like to comment on my experience in this thread, please.
