### ISSUE TITLE
Type definition file for TypeScript is missing

### ISSUE THREAD

**Issue by Chris2011** [scrumpy/tiptap#439] opened 2019-08-27 12:02 UTC
**Is your feature request related to a problem? Please describe.**
When I use TypeScript and import this lib, I got the error inside of VSCode and via serve, that the typedef file is missing. If it is easy for you, please add it. Otherwise, I will have a look later to generate one, when I have time.

**Describe the solution you'd like**
Creating a .d.ts file

**Additional context**
Context is, using your plugin with TypeScript in Vue.

**Comment by philippkuehn** [comment] 2019-08-27 12:04
Duplicate of #54

**Closed by philippkuehn** 2019-08-27 12:04 UTC
Labels: feature request
