### ISSUE TITLE
Collaborative Editing

### ISSUE THREAD

**Issue by thomasaull** [scrumpy/tiptap#74] opened 2018-10-31 13:19 UTC
Are there any plans on implementing collaborative editing for this plugin? Any pointers on how to start on this?

Prosemirror Demo: https://prosemirror.net/examples/collab/#edit-Example
Prosemirror Docs: https://prosemirror.net/docs/guide/#collab

**Comment by thomasaull** [comment] 2018-10-31 15:30
Ok I got it working locally with two editors as long as I delete content. As soon as I try to add content I get an error. Maybe I can work it out though :)

**Comment by thomasaull** [comment] 2018-10-31 17:46
I'm stuck… 

I tried to create a basic example based on https://prosemirror.net/docs/guide/#collab and the tiptap editor. It works, if I delete content. As soon as I try to add any character the following error occurs: `TransformError: Invalid content for node paragraph`

I suspect it has something to do with the underlying schema, I'm totally new to prosemirror though. Maybe you can give me a hand, since you probably know more about all the underlying structures. I created a minimal testrepo here: https://github.com/thomasaull/tiptap-collab

**Comment by philippkuehn** [comment] 2018-11-04 11:41
Hey @thomasaull,

thank you for using tiptap. Support for the collaboration plugin was always on my list but I never found time to look into it. And I definitely need this for Scrumpy 😅 I can reproduce your issue but I'm not sure if this is related to tiptap. Unfortunately the collab demo on the Prosemirror page is very hard to understand. 😩

Maybe we could try to build your collab example in native JS to check if the error still occurs and ask for help on [https://discuss.prosemirror.net/](https://discuss.prosemirror.net).

**Comment by thomasaull** [comment] 2018-11-04 11:54
@philippkuehn I actually did a bit more testing last week with the native JS prosemirror library. It did work and apparently it has to do with the schema, but it's a bit weird. What I found out:

- When I create the schema in both of the instances of the Editor seperately, it throws the error
- When I import the schema from an external file **or** pass it through a prop from `Authority.vue` it works

So I guess, the error does not happen if you have an actual collaboration use case (just one editor in your Browser syncing via a server). If you're interested you can check the example here: https://github.com/thomasaull/tiptap-collab/commit/af8701a91eb1992be813fb01088e29803cd80c61 (Note: It's using `RawEditor.vue` instead of `Editor.vue`)

**Comment by philippkuehn** [comment] 2019-02-03 11:59
@thomasaull Better late than never! I found the initial issue with integrating the collab plugin into tiptap. Will release a working demo soon! 👍

**Comment by thomasaull** [comment] 2019-02-04 09:58
Awesome, looking forward to it @philippkuehn :)

**Comment by philippkuehn** [comment] 2019-02-04 10:57
@thomasaull the problem in our implementation is dispatching the transaction.

```js
const transaction = receiveTransaction(
  view.state,
  newData.steps,
  newData.clientIDs
)
```

every step in `newData.steps` is still a `Step` class. In a real world example these steps would be a plain object (because these are received via web sockets or whatever) and you have to bind the prosemirror schema to it like this:

```js
import { Step } from 'prosemirror-transform'
// ...
const transaction = receiveTransaction(
  view.state,
  newData.steps.map(step => Step.fromJSON(schema, step)),
  newData.clientIDs,
)
```
So for your simplified example of directly communicating editors you have to do something like this:

```js
import { Step } from 'prosemirror-transform'
// ...
const transaction = receiveTransaction(
  view.state,
  JSON.parse(JSON.stringify(newData.steps.map(step => Step.fromJSON(schema, step)))),
  newData.clientIDs,
)
```

**Comment by xerosanyam** [comment] 2019-02-26 05:46
any updates on this 😅

**Comment by xerosanyam** [comment] 2019-02-26 05:54
Hi there! Amazing work on tiptap. 👏 
Just wanted to know if I can implement collaboration using prosemirror-collab or we need this feature to be implemented before one can use the feature.
I mean what is the difficulty if one tries to use the native collaboration feature.

**Comment by alangibson** [comment] 2019-04-01 17:57
It looks like @philippkuehn found a workaround for this issue, but the status is still Open. Are you planning on releasing a fix for this or should we just go with the workaround?

**Comment by kwiesmueller** [comment] 2019-04-15 22:51
Would need that feature too, is there any work done on this or would we have to stick to the workaround?

**Comment by philippkuehn** [comment] 2019-04-16 18:09
Hey, the prosemirror-collab plugin is not easy to use because you have to use it at your frontend and backend. I didn't find a way to get this running perfectly on my first try. And the [default example](https://prosemirror.net/examples/collab/#edit-Example) of prosemirror-collab is unnecessary complex with an absurd feature overload. 😩

But we plan to add collaborative editing into our editor at scrumpy in the next weeks. When done I will provide a working demo with a socket server at the examples page. 💪

**Comment by philippkuehn** [comment] 2019-05-03 20:17
Good news: collaboration is finally working! Can hopefully release it the next days.

**Comment by philippkuehn** [comment] 2019-05-06 10:55
It's done! 🎉
A collaboration demo is online [here](https://tiptap.scrumpy.io/collaboration).
You can see the client-side implementation [here](https://github.com/scrumpy/tiptap/blob/master/examples/Components/Routes/Collaboration/index.vue).
You can see the server-side implementation [here](https://glitch.com/edit/#!/tiptap-sockets).

**Closed by philippkuehn** 2019-05-06 10:55 UTC
Labels: feature request, help wanted

**Comment by jeromepin** [comment] 2019-05-08 10:34
Nice work ! 😃 The server-side implementation relies on `prosemirror-transform` to manipulate step according to the schema. What would be necessary to have a such server in another language ? Reimplement functions from `prosemirror-transform` ?

**Comment by philippkuehn** [comment] 2019-05-08 10:44
@jeromepin This is indeed a tough challenge. We will implement collab into scrumpy over the next weeks. Our backend built on PHP so we will try to communicate between a PHP and Node server 🤞

I know there are some other ideas of implemention collab server-side in the [forum](https://discuss.prosemirror.net/search?q=collab).

**Comment by jeromepin** [comment] 2019-05-08 10:52
@philippkuehn Can you tell us why you chose to add the Node server (and handle the inter-process communication) rather than implement the server-side stuff in PHP ? Less work to do maybe ?

**Comment by kwiesmueller** [comment] 2019-05-08 10:59
@jeromepin I plan to build a Golang server implementation for this in the next few days. Hope to have some good shareable results soon.
Happy to keep you posted.

**Comment by qyloxe** [comment] 2019-05-08 11:01
Can you tell us who is "us" in your question? Jerome and Pin are two
persons?
:-)
sorry, cant help myself :-)

**Comment by jeromepin** [comment] 2019-05-08 11:17
@kwiesmueller I don't know yet which language I'm gonna use but I'll be happy to see what you will do with Go. I see there is some port in [Python](https://github.com/fiduswriter/prosemirror-python).

@qyloxe Can you tell us who is "us" in your question ? 😛  It works both ways ! Btw, we are way more than two in my head 😂

**Comment by wahengchang** [comment] 2019-05-26 09:23
@thomasaull did you come up with any solution ?
i m trying with a realtime db, firebase, as the db. and looking for vue components solution on the frontend side. no luck til now. :(

**Comment by philippkuehn** [comment] 2019-05-26 09:27
@wahengchang the [collab example](https://tiptap.scrumpy.io/collaboration) doesn't help you?

**Comment by wahengchang** [comment] 2019-05-26 10:25
@philippkuehn this is very helpful example with both demo and source code.

Because my backend server is `Firebase` realtime database, It seem like I have a lot to do in modifying the interfaces on both `soket.io` server and vue module (`onInit()`), for fetching data and update data work.

**Comment by wahengchang** [comment] 2019-05-26 12:15
@philippkuehn , everything working so great with `firebase` realtime database. just two little things bothering me. 
 - losing focus when it update/`Editor.destory()`
 - having problem integrating with codehighlight.

if there is more info please let me know (I did read the doc `tiptap.scrumpy.io`).

**Comment by wahengchang** [comment] 2019-05-26 12:17
not sure if i have the luck to have more support, there is how i use Edit:
https://github.com/wahengchang/realtime-js-editor/blob/master/components/rooms/EditorCore.vue

**Comment by philippkuehn** [comment] 2019-05-27 08:19
@wahengchang 

> losing focus when it update/Editor.destory()

update and destroy are two completely different things. On update, focus should be the same. On destroy the editor is losing focus.

> having problem integrating with codehighlight

what is the *problem*? can you share a codesandbox/gif/screencast?

> why do we save the field steps on socket.io exmaple? as I see steps will never be used.

Of course this steps will be used. And I think that your solution won't work as expected. A server has to check if the stored version is the same as the clients version. If so all steps will be applied to the stored document on the server and all steps are sent back to all clients. You'll also receive your own steps again. In this moment these steps are getting *confirmed*. Now you know that you don't have to send these steps again (the collab extension is doing that for you). I also implemented *locking* on the server side to prevent that two simultaneous requests won't overwrite each other.

Maybe it's helpful to read [this](https://prosemirror.net/docs/guide/#collab), [this](http://marijnhaverbeke.nl/blog/collaborative-editing.html) and [this](https://discuss.prosemirror.net/t/how-to-handle-edge-case-with-collab-module/288) resource for a better understanding.

**Comment by bbbford** [comment] 2019-06-12 15:47
@philippkuehn - First of all, thank you for all of you hard work! I have managed to get collaboration working, however one question remains at the moment -

On the server, we check for version mismatch. If there is a mismatch, we send steps back to user and return.

```
    // version mismatch: the stored version is newer
    // so we send all steps of this version back to the user
    if (storedData.version !== version) {
      socket.emit('update', {
        version,
        steps: getSteps(version),
      })
      storeLocked(false)
      return
    }
```

So, the user gets the needed steps and he is now on the correct version.

However, upon receiving these updated steps, the client still has unconfirmed changes that need to be applied. It appears that we are not attempting to resend the unconfirmed changes from the client until the user actually types something into the editor. What if the user does not type any more changes into the editor and closes? Then his unconfirmed changes would be lost.

According to ProseMirror docs - 

> When a set of steps gets rejected by the authority, they will remain unconfirmed until, supposedly soon after, we receive new steps from the authority. After that happens, because the onNewSteps callback calls dispatch, which will call our dispatchTransaction function, the code will try to submit its changes again.

So, here is my question -
When the client receives and applies steps from the server, should it not also attempt to resend any unconfirmed changes?

Perhaps that would go in the update function?
```
  get defaultOptions() {
    return {
      version: 0,
      clientID: Math.floor(Math.random() * 0xFFFFFFFF),
      debounce: 250,
      onSendable: () => {},
      update: ({ steps, version }) => {
        const { state, view, schema } = this.editor

        if (getVersion(state) > version) {
          return
        }

        view.dispatch(receiveTransaction(
          state,
          steps.map(item => Step.fromJSON(schema, item.step)),
          steps.map(item => item.clientID),
        ))
      },
    }
  }
```

**Comment by LionsAd** [comment] 2019-06-12 21:43
We are going into a different direction:

We will likely use https://github.com/y-js/y-prosemirror/tree/master to bind prosemirror to yJS.

The advantage of that approach is that due to the usage of CRDT (instead of OT) the server-side component can be really light (and probably even be implemented in go or python or ...).

Here is an older example, which is really simple IMHO - given how complex collab is:

https://yjs.website/tutorial-prosemirror.html#

I kinda liked the approach as prosemirror's collab works more like GIT and less like OT (ShareDB, Google Docs) or CRDT (Apple Notes).

**Comment by milahu** [comment] 2021-12-30 21:48
related: [Offline, Peer-to-Peer, Collaborative Editing using Yjs](https://discuss.prosemirror.net/t/offline-peer-to-peer-collaborative-editing-using-yjs/2488)

**Comment by hanspagel** [comment] 2021-12-30 22:08
related: https://tiptap.dev/guide/collaborative-editing
