### ISSUE TITLE
Feature Request: open link in new tab

### ISSUE THREAD

**Issue by micahzev** [scrumpy/tiptap#240] opened 2019-03-18 21:19 UTC
hey scrumpy - thanks for a wonderful library. renderless is the future!

would it be possible to be able to set the links as open in new tab? we dont always want to navigate our users away from the current tab.

thanks and stay vuetiful!

**Comment by panayotisk** [comment] 2019-03-19 15:23
Hey @micahzev, have you checked this issue? 
https://github.com/scrumpy/tiptap/issues/161

**Comment by micahzev** [comment] 2019-03-23 02:18
@panayotisk thanks! ill try this out on our implementation

**Comment by philippkuehn** [comment] 2019-04-30 15:05
Duplicate of #161

**Closed by philippkuehn** 2019-04-30 15:05 UTC
