### ISSUE TITLE
Provide a Link extension example which doesn't use EditorMenuBubble 

### ISSUE THREAD

**Issue by SnakeyHips** [scrumpy/tiptap#432] opened 2019-08-21 08:57 UTC
I'm trying to implement use of the link extension and I'm having trouble working out how to apply the text within the a link without the use of the EditorMenuBubble. I'm basically trying to implement something like:

```
showLinkPrompt(command) {
    const linkText = prompt("Enter the text for your link");
    const linkUrl = prompt("Enter the URL of your link");
    if (linkText && linkUrl) {
      command({text: linkText, href: linkUrl});
    }
  }
```

However, I'm having trouble working out how to send the link object into the command function with both a linkText and linkUrl. Sorry if this has been documented somewhere but I haven't been able to find it or figure out how it's done within the given example as it seems to be done within the EditorMenuBubble.

Thanks!

**Comment by SnakeyHips** [comment] 2019-08-23 09:25
Just found out you can highlight text and then enter the URL of the link using a prompt like:

```
showLinkPrompt(command) {
    const linkUrl = prompt("Enter the URL of your link");
    if (linkUrl) {
      command({href: linkUrl});
    }
  }
```

Still would be nice to be able to do both the text and url manually but I guess this method still works without using EditorMenuBubble!

**Comment by philippkuehn** [comment] 2019-08-24 11:16
Yeah I’ll do this.

duplicate of #373

**Closed by philippkuehn** 2019-08-24 11:16 UTC
Labels: feature request
