### ISSUE TITLE
Placeholder text appears even when the editor is not empty

### ISSUE THREAD

**Issue by steveneal** [scrumpy/tiptap#487] opened 2019-10-10 00:25 UTC
The placeholder depends on the following CSS selector:

```
p.is-empty:first-child::before {
  content: attr(data-empty-text);
  float: left;
  color: lightgray;
  pointer-events: none;
  height: 0;
}

```
The **is-empty** class is added to the first paragraph when it contains no text. The effect of this is that the placeholder text appears when then he first paragraph of the document is empty, regardless of whether there is subsequent text.

**Steps to Reproduce / Codesandbox Example**
1. Go to the placeholder demo page
2. Enter a line of text but leave the first paragraph empty
3. Move the cursor into the first paragraph and the placeholder appears

**Expected behavior**
The placeholder text should only appear when the document is empty

**Screenshots**
<img width="369" alt="Screenshot 2019-10-09 at 20 21 49" src="https://user-images.githubusercontent.com/342829/66529804-d808d500-ead2-11e9-8822-032b679e151d.png">

**Comment by philippkuehn** [comment] 2019-10-10 09:14
Duplicate of #463

**Closed by philippkuehn** 2019-10-10 09:14 UTC
Labels: bug
