### ISSUE TITLE
Provide proper docs on how to use this component in an app

### ISSUE THREAD

**Issue by bhaidar** [scrumpy/tiptap#466] opened 2019-09-28 19:10 UTC
I tried to use this component in a Vue app however I was not lucky in terms of maintaining the styles and look and feel of that of the examples pages.

I would be great if you can provide a docs to explain in detail how to integrate this component in a Vue app and maintain the proper styling.

For instance all H1 tags were converted to P tag in the app. Maybe there are missing files or some classes need to be registers with Vue component? 

Thanks

**Comment by philippkuehn** [comment] 2019-09-29 04:33
duplicate of #162

**Closed by philippkuehn** 2019-09-29 04:33 UTC
Labels: feature request
