### ISSUE TITLE
 Error in nextTick on conditional loading

### ISSUE THREAD

**Issue by SPQRInc** [scrumpy/tiptap#102] opened 2018-11-19 16:50 UTC
Hello there :-)

I have to do something like this:

```
<div v-if="isActive">
  <editor :content="myContent"></editor>
</div>
```

`<editor>` is my custom tiptap component

Well - if I do so, I am getting this **error**:

```
[Vue warn]: Error in nextTick: "TypeError: Argument 1 ('node') to Node.appendChild must be an instance of Node"

found in

---> <EditorContent>
<Editor> at resources/assets/js/components/Editor.vue
``` 

This is my component:

```
<template>
    <div class="editor">
        <editor-menu-bar :editor="editor">
            <div class="menubar" slot-scope="{ commands, isActive }">
                <button>
                    ...
                </button>
            </div>
        </editor-menu-bar>
        <editor-content class="editor__content" :editor="editor"/>
    </div>
</template>
<script>
import {Editor, EditorContent, EditorMenuBar} from 'tiptap'

import {
	Blockquote,
	BulletList,
	CodeBlock,
	ListItem,
	OrderedList,
	Bold,
	Code,
	Italic,
	Strike,
	Placeholder
} from 'tiptap-extensions'

export default {
	name: "editor",
	components: {
		EditorContent,
		EditorMenuBar
	},
	props: {
		content: {
			type: String,
			default: ''
		}
	},
	data () {
		return {
			editor: new Editor ({
				extensions: [
					new Blockquote (),
					new BulletList (),
					new CodeBlock (),
					new ListItem (),
					new OrderedList (),
					new Bold (),
					new Code (),
					new Italic (),
					new Strike (),
					new Placeholder ({
						emptyClass: 'is-empty',
					})
				],
				content: '',
				onUpdate: ({getHTML}) => {
					let content = getHTML ();
					this.$emit ('update', content)
				},
			}),
		}
	},
	mounted () {
		this.setContent ();
	},
	beforeDestroy () {
		this.editor.destroy ()
	},
	methods: {
		setContent () {
			this.editor.setContent (this.content);
		},
	},
}
</script>
```

Well - if I don't use the `v-if` condition, everything works fine. But unfortunately I have to do it this way.

My question: How can I solve this?

**Comment by philippkuehn** [comment] 2018-11-20 08:53
Hey @SPQRInc, do you use the lastest version of tiptap? I think this should be fixed in one of the latest updates.

**Comment by SPQRInc** [comment] 2018-11-20 16:40
Hi @philippkuehn and thank you for your response.

Yes, I think I am using the lastest (`1.0.5`):

```
npm show tiptap version
1.0.5
```

**Comment by SPQRInc** [comment] 2018-11-20 17:02
As a workaround, I did this:

```
data () {
		return {
			/*			editor: new Editor ({
                            extensions: [
                                new Blockquote (),
                                new BulletList (),
                                new CodeBlock (),
                                new ListItem (),
                                new OrderedList (),
                                new Bold (),
                                new Code (),
                                new Italic (),
                                new Strike (),
                                new Placeholder ({
                                    emptyClass: 'is-empty',
                                })
                            ],
                            content: '',
                            onUpdate: ({getHTML}) => {
                                let content = getHTML ();
                                this.$emit ('update', content)
                            },
                        }),*/
			editor: null
		}
	},
mounted () {
		this.editor = new Editor ({
			extensions: [
				new Blockquote (),
				new BulletList (),
				new CodeBlock (),
				new ListItem (),
				new OrderedList (),
				new Bold (),
				new Code (),
				new Italic (),
				new Strike (),
				new Placeholder ({
					emptyClass: 'is-empty',
				})
			],
			content: '',
			onUpdate: ({getHTML}) => {
				let content = getHTML ();
				this.$emit ('update', content)
			},
		});
```

Works so far :-)

**Comment by philippkuehn** [comment] 2018-12-19 21:22
Closed due to inactivity

**Closed by philippkuehn** 2018-12-19 21:22 UTC

**Comment by modstore** [comment] 2019-02-06 03:04
I encountered this error just now. I updated your sandbox link to reproduce the error: https://codesandbox.io/s/m2kq26z0p

Basically I want to be able to show and hide the editor by clicking a button. This error happens when the editor is enclosed within a v-if. In the example, click the "toggle" button a few times to see it happen.

**Comment by altsst** [comment] 2022-10-31 07:42
I experience the same problem with React.
![image](https://user-images.githubusercontent.com/116441438/198956617-a822bccc-240a-4888-bcde-3a245bb7bba3.png)

package.json: `"@tiptap/react": "^2.0.0-beta.199",`
