### ISSUE TITLE
Font Size, Font Family, Text Color

### ISSUE THREAD

**Issue by vedmant** [scrumpy/tiptap#388] opened 2019-07-16 09:03 UTC
Hi, this editor really lacks of very important features of rich text editor like Font Size, Font Family and Text Color. There is also no examples of how this can be implemented. Currently I'm trying to find a way to do this, but still have no luck. Could you at least show some working examples of how this can be achieved?

**Comment by jeromepin** [comment] 2019-07-16 14:24
Maybe with a [custom Mark extension](https://github.com/scrumpy/tiptap#create-custom-extensions) ? I think it's pretty easy (I never did it though) to create an extension rendering a `<p class="text-color-red">` based on common [mark extensions](https://github.com/scrumpy/tiptap/tree/master/packages/tiptap-extensions/src/marks). Is it what you are looking for ?

**Comment by vedmant** [comment] 2019-07-16 14:59
@jeromepin Yes, but there is no usable example in there. I managed to make it work partially with mark extension but still there is issue with isActive, it just responds active for all fonts. Here is my code:

```
import {Mark} from 'tiptap'
import {updateMark} from 'tiptap-commands'

export default class FontFamily extends Mark {
  get name() {
    return 'font_family'
  }

  get schema() {
    return {
      attrs: {
        font_family: {
          default: '',
        },
      },
      content: 'inline*',
      group: 'block',
      draggable: false,
      parseDOM: [{
        style: 'font-family',
        getAttrs: mark => ({font_family: mark})
      }],
      toDOM: mark => ['span', {style: `font-family: ${mark.attrs.font_family}`}, 0],
    }
  }

  commands({type}) {
    return (attrs) => updateMark(type, attrs)
  }
}
```

The problem here is that unlike existing mark extensions this one has custom parameter passed `font_family` and I can't find any example of how to correctly do this. Heading example doesn't work as it's not using styles.

**Comment by jeromepin** [comment] 2019-07-17 15:49
@vedmant Indeed, it's not that easy, my bad :) I'm trying too but I'm not going anywhere... If you come up with a solution, I will be interested to see it !

**Comment by vedmant** [comment] 2019-07-18 10:25
@jeromepin 

Yes, it can be done much simpler:
```
toDOM: mark => ['span', {style: mark.attrs.font_family ? `font-family: ${mark.attrs.font_family}` : ''}, 0],
```
But it still leaves span tag with empty style attr.

Another issue is that it works only if I first select text and then change font size, it doesn't work if I first select font size and then start typing.

Also it generates lots of nested spans like this:
```
<span style="font-family: Helvetica, sans-serif"><span style="font-size: 14pt"><span style="color: #3300ff">test</span></span></span>
```

As I understand there is no way to make it understand that it doesn't need multiple spans?

**Comment by jeromepin** [comment] 2019-07-18 13:20
@vedmant About your multiple nested span issue, I think the "fix" is to be made in tiptap's core. Try to add both _Bold_ and _Italic_ to a word, it will create `p>strong>em`. It would require to check if the current tag is the same kind as the one we want to add, then add to it's style rather than add a new tag.

**Comment by kuoruan** [comment] 2019-07-25 09:34
Any way to avoid nested spans?
My code:
```
import { Mark } from "tiptap";
import { updateMark, markInputRule, removeMark } from "tiptap-commands";

export default class FontFamily extends Mark {
  get name() {
    return "fontFamily";
  }

  get schema() {
    return {
      attrs: {
        fontFamily: {
          default: "arial"
        }
      },
      content: "inline*",
      group: "block",
      draggable: false,
      parseDOM: [
        {
          style: "font-family",
          getAttrs: (mark: any) => ({ fontFamily: mark })
        }
      ],
      toDOM: (mark: any) => [
        "span",
        { style: `font-family: ${mark.attrs.fontFamily}` },
        0
      ]
    };
  }

  commands({ type }: any) {
    return (attrs: any) => {
      if (attrs.fontFamily) {
        return updateMark(type, attrs);
      }
      return removeMark(type);
    };
  }

  inputRules({ type }: any) {
    return [markInputRule(/(?:\*\*|__)([^*_]+)(?:\*\*|__)$/, type)];
  }
}
```

**Comment by vedmant** [comment] 2019-07-25 10:08
@kuoruan I have an idea to create single mark for font family / size / color, this may it may be working with a single span, not sure however.

**Comment by kuoruan** [comment] 2019-07-25 10:50
@vedmant Any example code? Thanks.

**Comment by philippkuehn** [comment] 2019-08-20 14:06
Duplicate of #64, #84

**Closed by philippkuehn** 2019-08-20 14:06 UTC
Labels: feature request

**Comment by vedmant** [comment] 2019-08-20 14:28
@philippkuehn That two are closed and not resolved properly. This are important things, people will be just creating new issues for this.

**Comment by philippkuehn** [comment] 2019-08-20 14:30
@vedmant These issues are still open for further discussion. This won't change anything that I don't have plans to add this to the core.

**Comment by vedmant** [comment] 2019-08-20 14:32
@philippkuehn Why don't you add the very essential features for rich text editor like font size and color?

**Comment by philippkuehn** [comment] 2019-08-20 14:39
@vedmant I'm waiting for very essential PRs.

**Comment by vedmant** [comment] 2019-08-20 14:48
@philippkuehn You just said you don't have plans to add this to core, now you offer somebody to add a PR? Yet you closed the issue. Doesn't look like you can make up your mind.

**Comment by philippkuehn** [comment] 2019-08-20 17:20
Ok. Let me explain why I don't want to add this to the core now:

@vedmant It's not *essential*. There are so many usecases where you don't need this. Think of creating a comment, a tweet, a slack message. All places for text editors where this isn't a requirement. And personally I'm happy to don't work with CMS anymore, where you can change this kind of *styling*, because it's a nightmare to maintain as a developer.

Also it's kind of hard to implement in the current system of isolated nodes and marks. At the moment every node and mark has its own tag. And that's a good thing. When implementing *styling* there are several ways to do it:

1. one mark per styling (easy to implement)

```html
<p>
  <strong>
    <em>
      <span style="font-family: Arial">
        <span style="font-size: 20px">
          <span style="color: red">
            Hey
          </span>
        </span>
      </span>
    </em>
  </strong>
</p>
```

2. a combined font-style mark (harder to implement)

```html
<p>
  <strong>
    <em>
      <span data-font-style style="font-family: Arial; font-size: 20px; color: red">
        Hey
      </span>
    </em>
  </strong>
</p>
```

3. implemented in existing nodes (hardest to implement)

```html
<p style="font-family: Arial; font-size: 20px; color: red">
  <strong>
    <em>
      Hey
    </em>
  </strong>
</p>
```

Each of these solutions has its pros and cons. None really convinces me.

**Comment by xlcrr** [comment] 2019-11-14 17:16
Bump, really need this ! <3

**Comment by JerGallagher-TMobile** [comment] 2020-01-27 22:49
> @vedmant Ok. Let me explain why I don't want to add this to the core now:
> 
> It's not _essential_. There are so many usecases where you don't need this. Think of creating a comment, a tweet, a slack message. All places for text editors where this isn't a requirement. And personally I'm happy to don't work with CMS anymore, where you can change this kind of _styling_, because it's a nightmare to maintain as a developer.
> 
> Also it's kind of hard to implement in the current system of isolated nodes and marks. At the moment every node and mark has its own tag. And that's a good thing. When implementing _styling_ there are several ways to do it:
> 
> 1. one mark per styling (easy to implement)
> 
> ```
> <p>
>   <strong>
>     <em>
>       <span style="font-family: Arial">
>         <span style="font-size: 20px">
>           <span style="color: red">
>             Hey
>           </span>
>         </span>
>       </span>
>     </em>
>   </strong>
> </p>
> ```
> 
> 1. a combined font-style mark (harder to implement)
> 
> ```
> <p>
>   <strong>
>     <em>
>       <span data-font-style style="font-family: Arial; font-size: 20px; color: red">
>         Hey
>       </span>
>     </em>
>   </strong>
> </p>
> ```
> 
> 1. implemented in existing nodes (hardest to implement)
> 
> ```
> <p style="font-family: Arial; font-size: 20px; color: red">
>   <strong>
>     <em>
>       Hey
>     </em>
>   </strong>
> </p>
> ```
> 
> Each of these solutions has its pros and cons. None really convinces me.

It is required if TipTap is to be adopted as a competitive Rich Text Editor to CKEditor which can handle font family and color styling.
https://ckeditor.com/docs/ckeditor5/latest/features/font.html

**Comment by vsirghii** [comment] 2020-01-28 04:15
The word "**Reach**" in the name of tiptap component "Reach Text Editor" is really misleading. I spent one day for implementing tiptap in my solution and hit the road block having no such features like font sizes and colors. Didn't really expect this for something rich.
Another thing, why it is so complicated and so many discussions are going on around the basic text editor functionality?
I just simply continued research and found a straight forward component, which works out of the box and has all the basic functionality for a reach text editor: quill-editor https://www.vuetoolbox.com/projects/vue-quill-editor

**Comment by gregveres** [comment] 2020-08-28 01:07
As someone who just spent a couple days investigating which editor to use and deciding to use tiptap, I can tell you that my first impressions were higher than my current impressions, but now that I have spent a couple of days integrating it into my app, I am happy with the result and where the functionality of my app is going. 

However, I do wonder why something like font size and font color are not part of the standard set of extensions. I believe that given the current structure (and hopefully the 2.0 structure), that having a lot of extensions doesn't bloat every app's code  base because they import just the extensions that they need. So I see having these extensions as important for a full featured component, but sure not everybody is going to use them in their particular application. Look at this edit control we are using here on GitHub, it doesn't have font size and colour. My application requires it, so I will take a crack at trying to implement a custom extension for them.
I do think that because tiptap is "renderless", that having a standard extension for font family is more problematic. This isn't going to work out of the box for any app that decides to use it because those fonts are going to have to be loaded and available when rendering the html. But colour and size are standard things.

**Comment by herrdu** [comment] 2021-03-22 17:29
>     return [markInputRule(/(?:\*\*|__)([^*_]+)(?:\*\*|__)$/, type)];

我觉的  ‘updateMark’  有一些问题，我写了一个新的方法。
```
import {MarkType} from 'prosemirror-model';
import {EditorState, Transaction} from 'prosemirror-state';

export function toggleAndUpdateMark(type: MarkType, attrs: {[key: string]: any}) {
  return (state: EditorState, dispatch: (tr: Transaction) => void) => {
    const {tr, selection, doc} = state;

    const {empty} = selection;
    if (empty) {
      const attrsKeys = Object.keys(attrs);

      if (state.storedMarks && type.isInSet(state.storedMarks)) {
        dispatch(state.tr.removeStoredMark(type));
        if (attrsKeys.length > 0) {
          return dispatch(state.tr.addStoredMark(type.create(attrs)));
        }
      } else {
        if (attrsKeys.length > 0) {
          return dispatch(state.tr.addStoredMark(type.create(attrs)));
        }
      }
    } else {
      const {from, to} = selection;

      const hasMark = doc.rangeHasMark(from, to, type);

      if (hasMark) {
        tr.removeMark(from, to, type);
      }

      tr.addMark(from, to, type.create(attrs));

      return dispatch(tr.scrollIntoView());
    }
  };
}
```

**Comment by herrdu** [comment] 2021-03-22 17:30
>         return updateMark(type, attrs);

```
我觉的 ‘updateMark’ 有一些问题，我写了一个新的方法。

import {MarkType} from 'prosemirror-model';
import {EditorState, Transaction} from 'prosemirror-state';

export function toggleAndUpdateMark(type: MarkType, attrs: {[key: string]: any}) {
  return (state: EditorState, dispatch: (tr: Transaction) => void) => {
    const {tr, selection, doc} = state;

    const {empty} = selection;
    if (empty) {
      const attrsKeys = Object.keys(attrs);

      if (state.storedMarks && type.isInSet(state.storedMarks)) {
        dispatch(state.tr.removeStoredMark(type));
        if (attrsKeys.length > 0) {
          return dispatch(state.tr.addStoredMark(type.create(attrs)));
        }
      } else {
        if (attrsKeys.length > 0) {
          return dispatch(state.tr.addStoredMark(type.create(attrs)));
        }
      }
    } else {
      const {from, to} = selection;

      const hasMark = doc.rangeHasMark(from, to, type);

      if (hasMark) {
        tr.removeMark(from, to, type);
      }

      tr.addMark(from, to, type.create(attrs));

      return dispatch(tr.scrollIntoView());
    }
  };
}
```

**Comment by philippkuehn** [comment] 2021-03-22 17:50
[tiptap 2](https://blog.ueber.io/post/tiptap-2-0-beta/) has support for font-size, font-family and color :)

**Comment by zealot128** [comment] 2021-05-06 14:23
I got a satisfying solution for Color:

- Using the TextStyle mark
- Copy&Paste the @tiptap/extension-font-family and replacing all FontFamily etc. through "Color"
- add a toolbar button with a dropdown (bootstrap-vue in our case), and iterating over every available color:

![Bildschirmfoto 2021-05-06 um 16 17 46](https://user-images.githubusercontent.com/147175/117314308-ea055200-ae86-11eb-83a9-e4dce7f971fb.png)

I could be made an extension for easier usage by other parties.

```javascript
// usage by toolbar:

<ColorPicker @select='setColor' :editor='editor'/>

...
methods: { setColor(color) { this.editor.chain().focus().setColor(color).run() } }
```

ColorPicker is a very simple component, dropdown with a listing of available colors, giving the selected color to the wrapper  via $emit. 

- helper: ``currentColor() {         return this.editor.getMarkAttributes("textStyle").color }`` good, for displaying currently used color/disabling reset button
- reset button: just emit a null/undefined color.

Let's see how to add font sizes, too...
