### ISSUE TITLE
setContent cursor goes to start?

### ISSUE THREAD

**Issue by arifhussain353** [scrumpy/tiptap#150] opened 2019-01-01 06:00 UTC
Hi there,

We have implemented tiptap on one of our projects, when setting the content dynamically after some event, the cursor goes to the start of the editor.

Is there any way to set the cursor to the position where it was already or move to the end of the position.

Thanks,

**Comment by antimodern** [comment] 2019-01-06 10:52
@arifhussain353 I have the same issue. Did you managed to fix it?

```js
watch: {
    value () {
      if (this.value) {
        this.editor.setContent(this.value)
        // this.html = this.editor.getHTML()
      }
    }
  }
```

Cursor jumps to start, when my async `value` is loaded. How to fix it?

**Comment by philippkuehn** [comment] 2019-01-06 11:57
Duplicate of #126

**Comment by philippkuehn** [comment] 2019-01-06 11:57
Duplicate of #126

**Closed by philippkuehn** 2019-01-06 11:57 UTC
