### ISSUE TITLE
Tippy instance is left alive after editor is destroyed

### ISSUE THREAD

**Issue by andreasvirkus** [scrumpy/tiptap#659] opened 2020-04-09 18:47 UTC
**Describe the bug**
Might be related to #214. The Suggestions tippy is kept alive even when the editor itself is destroyed, e.g.

```
<comment-editor v-if="editing" @keyup.native.esc="editing = false" />
```

When I now press `Escape`, the comment editor is removed, but if I had an active Suggestion decoration, its tippy is thrown to the top-left of the viewport

**Steps to Reproduce / Codesandbox Example**
1. Set up a `v-if` on the editor like I have above
2. Set up any `@keyup` handler to reverse the condition
3. Start entering a Suggestion (`@abc` by default)
4. If you see a tippy with suggestions, press the `@keyup` handler key from step 2
5. See that the editor is destroyed, but the tippy isn't

(I was unable to fork the Codesandbox official example because of https://github.com/scrumpy/tiptap/issues/316#issuecomment-611688759, so I've provided a GIF instead)

**Expected behavior**
The tippy is destroyed in the editor's destroy hook

**Screenshots**
![tiptap-escape](https://user-images.githubusercontent.com/9140811/78929793-ac7b9d00-7aab-11ea-98a7-9d05925183e0.gif)

**Environment**
 - OS: MacOS
 - Browser: Tested with Chrome & Firefox
 - Version: `1.26.8`

**Comment by andreasvirkus** [comment] 2020-04-09 19:16
As a workaround, using tiptap's [`hideAll`](https://atomiks.github.io/tippyjs/v6/methods/#hideall) method works

```
<comment-editor v-if="editing" @keyup.native.esc="stopEditing" />
```

```
import { hideAll } from 'tippy.js'

// ...
methods: {
  stopEditing() {
    hideAll({ duration: 0 })
    this.editing = false
  }
}
```

**Comment by philippkuehn** [comment] 2020-04-10 18:02
The suggestions example is now updated for tippy v6. It is fixed in this demo. And since tippy is not part of tiptap, I'll close this.

**Closed by philippkuehn** 2020-04-10 18:02 UTC
Labels: bug

**Comment by lowercasename** [comment] 2020-10-01 08:34
I believe I've just triggered the same error on the current demo (and it's happening on my own tiptap setup). To reproduce, start writing a suggestion, opening the tippy list, then delete the suggestion. If you do this a couple of times, the tippy window will end up on the top left of the window and doesn't go away. No errors in the console, and I haven't yet tried the workaround above (will try this week)!

I totally get that this isn't a priority as tippy is not part of tiptap, but if there's anything obvious to do to fix this, I'd be grateful to know!

**Comment by ozdemircibaris** [comment] 2023-08-07 09:33
`hideAll` worked for me too! Thanks!! @andreasvirkus
