### ISSUE TITLE
Cannot install Component/Icon

### ISSUE THREAD

**Issue by bromoapp** [scrumpy/tiptap#378] opened 2019-07-06 07:37 UTC
**Describe the bug**
I try to run code from Suggestions sample

**Steps to Reproduce / Codesandbox Example**
1. Create a new Vue project using CLI 3, install tiptap through npm
2. Cut and paste the code from [this](https://github.com/scrumpy/tiptap/blob/master/examples/Components/Routes/Suggestions/index.vue),
2. Install additional libs (sass-loader, node-sass, webpack, tiptap-extension, fuse.js, tippy.js)
3. Try to run npm install Components/Icon
4. See error like below

```
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t ssh://git@github.com/Components/Icon.git
npm ERR!
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bromo.kunto\AppData\Roaming\npm-cache\_logs\2019-07-06T07_31_56_818Z-debug.log
```

**Screenshots**

**Environment**
 - OS: Win 10
 - Browser chrome

**Comment by philippkuehn** [comment] 2019-07-06 09:53
Duplicate of #125

**Closed by philippkuehn** 2019-07-06 09:53 UTC
Labels: bug
